### ISSUE TITLE
In Firefox, PowerGlitch produces hundreds of console warnings on initialize

### ISSUE THREAD

**Issue by zstiles** [7PH/powerglitch#17]
When loading a page with PowerGlitch in Mozilla Firefox, the following console warning is seen:
`Keyframe property value “” is invalid according to the syntax for “transform”.`
This occurs upwards of **400 - 800 times** (it's not consistent) in rapid succession.

I am not seeing the issue in Google Chrome or Microsoft Edge.
In addition to my own project, this can be seen on the PowerGlitch homepage itself:
![screenshot](https://user-images.githubusercontent.com/6444559/208360732-7407b90c-3039-43e3-acf1-e353da633bcf.jpg)

**Comment by 7PH** [comment]
Hi @zstiles, I'll take a look once I'm back from vacations on Tuesday, thank you for reporting 👍

Could you please check your Firefox version in the meantime?

**Comment by zstiles** [comment]
I'm on `108.0.1 (64-bit)`, the latest version.

**Comment by 7PH** [comment]
I believe this should be an easy fix, replacing the empty string with none (1)

I'll make the fix when I'm back and bump the version 👍

(1): https://developer.mozilla.org/en-US/docs/Web/CSS/transform#formal_definition

**Comment by zstiles** [comment]
Excellent, and thanks for the great library! 👍

**Comment by 7PH** [comment]
Hi again @zstiles, `2.3.2` is published removing this warning 
Thank you for suggesting this fix 👍

**Comment by zstiles** [comment]
Looks good, thanks again! 🔥🔥🔥
