### ISSUE TITLE
Having issues using powerglitch

### ISSUE THREAD

**Issue by DAREALYTYGRUNN1NGARK456** [7PH/powerglitch#2]
I have tried to use powerglitch but it wont work you can see where i have tried it at
https://Power-glitch-api.darealytygrunn1.repl.co
And you can find the PowerGlitch.min.js file here
https://Power-glitch-api.darealytygrunn1.repl.co/powerglitch.min.js

**Comment by chrishau5** [comment]
I haven't been able to get powerglitch to work either

**Comment by 7PH** [comment]
Hi @DAREALYTYGRUNN1NGARK456 , in your example, the script that fetches the PowerGlitch iife bundle `<script src="/powerglitch.min.js"></script>` points to a 404: https://power-glitch-api.darealytygrunn1.repl.co/powerglitch.min.js 

Another comment on your code:
`const img = document.querySelector(".glitch")[0]`

should be
`const img = document.querySelector(".glitch")`

as you are using `querySelector` which returns null or an object, and not `querySelectorAll` which returns an array.

Here is a codepen example that mimics what you wants to do:
https://codepen.io/7PH/pen/dymeEZZ

Note that I copied and pasted the iife bundle from master: [dist/powerglitch.min.js](https://raw.githubusercontent.com/7PH/powerglitch/master/dist/powerglitch.min.js)

Hope that helps 😎

**Comment by 7PH** [comment]
Closing this issue for now
