### ISSUE TITLE
How can I destroy it?

### ISSUE THREAD

**Issue by kon3ko** [7PH/powerglitch#22]
After it's implemented in Vue and I change the page.
How do I destroy it?

**Comment by 7PH** [comment]
Hey, I missed the notification for this issue - Could you please clarify what you mean by destroying it?
Do you mean, having a way to cancel the glitch effect and revert back to what was shown originally? If yes, then I do not see the relation with changing page (your first sentence)
Please let me know what you have in mind 😉

**Comment by kon3ko** [comment]
@7PH I mean now I use it on nuxt2 when changing pages. I want to destroy What should I do?
I'm not sure If I don't destroy It may use more ram. And until the end may cause the web page to slow down or freeze.

**Comment by 7PH** [comment]
@kon3ko There should not be any memory leak when switching page as long as the glitched container is removed from the DOM.

PowerGlitch does interact with the DOM, which can mess with Vue's reconciliation with the VDOM in some cases:
- If the glitched element is the root node of a container
- If `v-if` and `v-glitch` are combined on a node
Excluding these two cases, there _should_ not be any memory leak. If you encounter something odd in your application, please create a reproducible example on StackBlitz for instance and I'll take a look. I'm closing this issue as wontfix, I'd re-open if there's something that can be improved in the future regarding this.
