### ISSUE TITLE
Wrong package type or TS configuration

### ISSUE THREAD

**Issue by rklos** [7PH/powerglitch#29]
Hi,
I have a Vite + Svelte project and I try to use the powerglitch.
When I import the package Vite reports the following error:
```bash
[vite] Error when evaluating SSR module /src/routes/components/box/Box.svelte: failed to import "powerglitch"
|- ReferenceError: exports is not defined in ES module scope
This file is being treated as an ES module because it has a '.js' file extension and '/Project/node_modules/powerglitch/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///Project/node_modules/powerglitch/lib/src/index.js:2:23
...
```
So the problem is that the `package.json` contains `"type": "module"`, but TypeScript configuration says the code should use CommonJS exports `"module": "commonjs",`. So the result is npm package marked as "ES6's modules ready" but with old-fashioned exports.
If you change the `package.json` or the `tsconfig.json` to match each other the problem will be solved.

**Comment by AaryanMadal** [comment]
maybe this will help
https://bit.ly/4gx42eQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by 7PH** [comment]
Hey, thanks a lot for noticing and taking the time to create an issue
You're absolutely right. I'll modify the published package to include both ESM and CJS bundles

See https://github.com/7PH/powerglitch/pull/30
