### ISSUE TITLE
Can something like this be realized

### ISSUE THREAD

**Issue by Wahrheit26** [7PH/powerglitch#3]
First of all thanks for this plugin!
I wonder if it can also implement the effect as in the following example?
https://codepen.io/tksiiii/details/xdQgJX

**Comment by 7PH** [comment]
Hi @Wahrheit26 ,
This looks close to what you are trying to do? https://jsfiddle.net/powerhat/hceztLm1/22/
Or are you thinking of a specific effect from the codepen you just sent?

**Comment by 7PH** [comment]
Hi again @Wahrheit26 , I am closing this issue, please let me know if you think there's more to it
