### ISSUE TITLE
Glitch on Hover

### ISSUE THREAD

**Issue by Code-Victor** [7PH/powerglitch#4]
Is it possible to have the glitch Effect onHover?

**Comment by 7PH** [comment]
That's an excellent idea - will be looking into it soon 😊

**Comment by Code-Victor** [comment]
awesome!

**Comment by 7PH** [comment]
Hi @Code-Victor , PR https://github.com/7PH/powerglitch/pull/5 should provide you with the asked functionnality 

Added an `playMode` optional option, which can accept these values:
- `always`: Always play the glitch, like now (default)
- `hover-triggered`: Will start glitching indefinitely after first hover
- `hover-only`: Will start glitching when hovering, and stop glitching when leaving the image

Still have to update the doc, check a few things and this will be merged/released in a few days

TY for the suggestion 👍

**Comment by Code-Victor** [comment]
wow, the speed of your response is out of this world!
Thanks for implementing it👍

**Comment by 7PH** [comment]
Hi @Code-Victor , you can already test it using the playground:
https://7ph.github.io/powerglitch/#/playground

You can use the new `recommended defaults` section at the top to select either `Once on hover` or `Always on hover` to have two examples of how you can use the new feature

Will be releasing `1.2.0` soon with this update

**Comment by Code-Victor** [comment]
works perfectly well for my use case. Thank you
